In [3]:
import numpy as np

In [4]:
xarr = np.array([12, 3, 5])

In [5]:
xarr.shape

(3,)

In [6]:
xarr.dtype

dtype('int32')

In [46]:
yarr = np.array([[1, 2], [3, 4], [5, 6]])  # shape = (b, h, w): (inner) w -> h -> b (outer)
yarr.shape

(3, 2)

In [48]:
yarr.sum(axis=0)  # mehtod: 객체 안에 있는 함수

array([ 9, 12])

In [49]:
np.mean(yarr, axis=0)

array([3., 4.])

In [54]:
np.concatenate((yarr, yarr), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

In [57]:
np.min(yarr, axis=1)

array([1, 3, 5])

In [58]:
np.multiply(yarr, yarr)

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [61]:
np.where(yarr<4, yarr, 0)

array([[1, 2],
       [3, 0],
       [0, 0]])

In [67]:
x = [[1, 2, 3]]
y = [[4, 5, 6]]

z = np.concatenate((x, y), axis=0).T

In [73]:
np.counat_nonzero(z>3)

3

In [78]:
x = [1, 2, 3, 4, 5]
y = x

In [79]:
y[0] = -1

In [80]:
x

[-1, 2, 3, 4, 5]

In [81]:
y

[-1, 2, 3, 4, 5]

In [159]:
x = np.genfromtxt('./Iris.csv', delimiter=',', skip_header=True)[:, :-1]
x[:5]

array([[1. , 5.1, 3.5, 1.4, 0.2],
       [2. , 4.9, 3. , 1.4, 0.2],
       [3. , 4.7, 3.2, 1.3, 0.2],
       [4. , 4.6, 3.1, 1.5, 0.2],
       [5. , 5. , 3.6, 1.4, 0.2]])

In [130]:
y = x[x[:, 0] > x[:, 0].mean(), :]
z = x[x[:, 0] <= x[:, 0].mean(), :]

In [131]:
y.shape

(70, 4)

In [132]:
z.shape

(80, 4)

In [128]:
x[:, 0] < x[:, 0].mean()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False,  True, False,  True, False,  True,  True, False, False,
       False,  True, False,  True,  True, False,  True, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True, False,  True, False, False, False,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,

In [149]:
np.savez('data.npz', my_z=z)

In [150]:
z1 = np.load('data.npz')

In [151]:
z1['my_z']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3